storageEdit:
  title: "&0Редактирование предметов"
scrollingEditFormats:
  selected: "{S} • [element]"
  notSelected: "&7 • &f[element]"
messages:
  unregisterTemplateError: "Шаблона [id] не существует!"
  unregisterMenuError: "Меню [id] не существует!"
  unregisterAnimationError: "Анимации [id] не существует!"
  unregisterTemplateSuccess: "Шаблон [id] успешно задерегистрирован!"
  unregisterMenuSuccess: "Меню [id] успешно задерегистрировано!"
  unregisterAnimationSuccess: "Анимация [id] успешно задерегистрирована!"
  reload: "Плагин успешно перезагружен!"
  menuIsNotExists: "Меню [id] не найдено!"
  playerIsOffline: "Игрок [player] оффлайн!"
  openMenuSuccess: "Меню [id] было успешно открыто для игрока [player]!"
  successfulMenuBuild: "Вы успешно создали новое меню [id]!"
  successfulTemplateBuild: "Вы успешно создали новый шаблон [id]!"
  converterIsNull: "Конвертер [id] не найден!"
  converterChestIsNull: "Вы должны обязательно посмотреть на хранилище перед конвертацией!"
  deluxeMenusFileIsNull: "Файл меню DeluxeMenus не существует!"